name: dom
author: Matan Lurey <matan@lurey.org>
description: A virtual DOM library for Dart
homepage: https://github.com/matanlurey/dom
version: 0.2.0

environment:
  sdk: '>=1.20.0 <2.0.0'

dependencies:
  collection: '^1.0.0'
  meta: '^1.0.0'
  quiver: '^0.24.0'

dev_dependencies:
  test: '^0.12.18+1'
